[git]
provider = "git-hub"
branch_prefix = "feature/"
main_branch = "main"
worktree_symlinks = []

[git.gitlab]
base_url = "https://gitlab.com"

[git.github]
owner = "ziims"
repo = "flock-tui"

[git.codeberg]
base_url = "https://codeberg.org"
ci_provider = "forgejo-actions"

[asana]
